apiVersion: v1
kind: Service
metadata:
  name: thelounge
  labels:
    app.kubernetes.io/name: thelounge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: thelounge
  ports:
    - name: http
      port: 9000
      targetPort: http
      protocol: TCP
