# CRDs are managed separately by OpenTofu.
crds:
  enabled: false

global:
  leaderElection:
    namespace: "${ namespace }"

clusterResourceNamespace: "${ namespace }"
namespace: "${ namespace }"

prometheus:
  servicemonitor:
    enabled: ${ prometheus_enabled }
