serverName: ${jsonencode(irc_conf.irc_domain)}
networkName: ${jsonencode(irc_conf.network_name)}
operPasswordHash: ${jsonencode(oper_password_hash)}
storageClass: ${jsonencode(irc_conf.storage_class)}
storageSize: ${jsonencode(irc_conf.ergo_storage_size)}
