image:
  repository: ghcr.io/ergochat/ergo
  tag: v2.19.1

serverName: irc.k8s.example.com
networkName: ExampleIRC
tlsSecretName: ergo-irc-tls
operPasswordHash: ""
storageClass: csi-rbd-sc
storageSize: 10Gi

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: "1"
    memory: 1Gi
